### ISSUE TITLE
Is the pre-trained model available for download for free anywhere?

### ISSUE THREAD

**Issue by matt-sharp** [akashmaity/RobustPPG#3]
@akashmaity The download link takes me to a page where I need to sign up for a Box account with a paid subscription.
Is it possible for you to supply an alternate link?  Thanks

**Comment by akashmaity** [comment]
The link is updated now. Please note that the linked model was trained on a limited PURE dataset, and needs to be trained on additional data for enhanced performance. I will update the code for training soon.

**Comment by matt-sharp** [comment]
Thanks @akashmaity
